language: node_js
node_js:
  - "node"
  - "6"
cache:
  yarn: true
install:
  - (cd rplugin/node/jsimport.js && yarn)
  - npm install -g codecov
  - yarn
script:
  - npm test
  - codecov
after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json
